# Generated by Django 2.2.6 on 2019-10-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=400, verbose_name='Subtítulo')),
                ('icon', models.CharField(choices=[('clock', 'Relógio'), ('gear', 'Engrenagem'), ('laptop', 'Notebook'), ('box', 'Cubo')], default='box', max_length=20, verbose_name='Ícone')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=400, verbose_name='Subtítulo')),
            ],
        ),
    ]
